export const categoryTabs = [
  {id: 'seeds', label: 'Seeds', icon: 'sprout'},
  {id: 'fertilizers', label: 'Fertilizers', icon: 'flask'},
  {id: 'pesticides', label: 'Pesticides', icon: 'bug'},
  {id: 'tools', label: 'Tools', icon: 'wrench'},
];

export const recommendedProducts = [
  {
    id: 'ssp-fertilizer',
    name: 'SSP Fertilizer',
    brand: 'COROMANDEL',
    image: require('../../assets/bazar/product1.jpg'),
    badge: 'Best for Soybean',
    rating: 4.7,
    reviews: '1.2k',
    price: 290,
    oldPrice: 349,
    unit: '/bag',
    category: 'fertilizers',
  },
  {
    id: 'chlorpyrifos-50ec',
    name: 'Chlorpyrifos 50EC',
    brand: 'BAYER CROPSCI',
    image: require('../../assets/bazar/product2.jpg'),
    badge: 'Protects Soybean',
    rating: 4.5,
    reviews: 890,
    price: 480,
    oldPrice: 669,
    unit: '/2l',
    category: 'pesticides',
  },
  {
    id: 'dap-fertilizer-rec',
    name: 'DAP Fertilizer',
    brand: 'IFFCO',
    image: require('../../assets/bazar/product3.jpg'),
    badge: 'Protects Crop',
    rating: 4.5,
    reviews: 812,
    price: 480,
    oldPrice: 620,
    unit: '/bag',
    category: 'fertilizers',
  },
];

export const allProducts = [
  {
    id: 'iffco-dap',
    name: 'DAP Fertilizer',
    brand: 'IFFCO',
    image: require('../../assets/bazar/product1.jpg'),
    badge: 'Bestseller',
    rating: 4.9,
    reviews: '3.4k',
    price: 1350,
    oldPrice: 1600,
    discount: '16% off',
    category: 'fertilizers',
    stock: true,
    sold: '5,200+',
    packSizes: ['5 kg', '50 kg', '100 kg'],
    selectedPack: '50 kg',
    description:
      'This fertilizer is best suited for your Soybean crop during the vegetative stage. Apply 100 kg/hectare for optimal yield improvement.',
    benefits: [
      'Rich in Nitrogen & Phosphorus',
      'Improves Root Growth',
      'Suitable for Irrigated Crops',
      'Long-lasting Nutrition',
    ],
  },
  {
    id: 'hybrid-maize',
    name: 'Hybrid Maize Seeds',
    brand: 'PIONEER SEEDS',
    image: require('../../assets/bazar/product2.jpg'),
    badge: 'New Arrival',
    rating: 4.6,
    reviews: '1.6k',
    price: 650,
    oldPrice: 780,
    discount: '17% off',
    category: 'seeds',
    stock: true,
  },
  {
    id: 'glyphosate',
    name: 'Glyphosate Weedicide',
    brand: 'MONSANTO',
    image: require('../../assets/bazar/product3.jpg'),
    rating: 4.4,
    reviews: 976,
    price: 380,
    oldPrice: 460,
    discount: '17% off',
    category: 'pesticides',
    stock: true,
  },
  {
    id: 'knapsack-sprayer',
    name: 'Knapsack Sprayer',
    brand: 'VENUS AGRO',
    image: require('../../assets/bazar/tractor.png'),
    badge: 'Top Rated',
    rating: 4.7,
    reviews: '2.2k',
    price: 1100,
    oldPrice: 1350,
    discount: '19% off',
    category: 'tools',
    stock: true,
  },
  {
    id: 'neem-oil',
    name: 'Neem Oil Organic',
    brand: 'ANAND AGRO',
    image: require('../../assets/bazar/product3.jpg'),
    badge: 'Organic',
    rating: 4.5,
    reviews: '1.1k',
    price: 280,
    oldPrice: 320,
    discount: '12% off',
    category: 'pesticides',
    stock: true,
  },
  {
    id: 'drip-kit',
    name: 'Drip Irrigation Kit',
    brand: 'NETAFIM',
    image: require('../../assets/bazar/drone.png'),
    badge: 'Premium',
    rating: 4.8,
    reviews: 567,
    price: 2400,
    oldPrice: 2900,
    discount: '17% off',
    category: 'tools',
    stock: true,
  },
];

export const recentlyViewed = [
  {
    id: 'mop-fertilizer',
    name: 'MOP Fertilizer',
    image: require('../../assets/bazar/product1.jpg'),
    price: 720,
    rating: 4.5,
  },
  {
    id: 'garden-tools',
    name: 'Garden Hand Tools',
    image: require('../../assets/bazar/product2.jpg'),
    price: 350,
    rating: 4.3,
  },
  {
    id: 'imidacloprid',
    name: 'Imidacloprid 17.8',
    image: require('../../assets/bazar/product3.jpg'),
    price: 420,
    rating: 4.6,
  },
];

export const applicationGuide = [
  {
    step: 1,
    title: 'Dosage',
    text: 'Apply 100 kg per hectare as basal dose. For top dressing, use 50 kg/hectare after 30 days of sowing.',
  },
  {
    step: 2,
    title: 'Application Method',
    text: 'Broadcast evenly or apply in furrows near root zone. Mix with moist soil for best absorption.',
  },
  {
    step: 3,
    title: 'Best Crop Stage',
    text: 'Vegetative & early reproductive stages. Apply before irrigation for maximum effectiveness.',
  },
  {
    step: 4,
    title: 'Safety Instructions',
    text: 'Store in a cool, dry place. Wear gloves during handling. Keep away from direct sunlight.',
  },
];

export const reviews = [
  {
    id: 1,
    name: 'Ramesh Patel',
    location: 'Maharashtra',
    time: '2 weeks ago',
    rating: 5,
    text: 'Excellent product! My soybean yield increased by 20% after using this. Delivery was on time and packaging was perfect. Highly recommend to all farmers.',
  },
  {
    id: 2,
    name: 'Sukhdev Singh',
    location: 'Punjab',
    time: '1 month ago',
    rating: 4.5,
    text: 'Good quality fertilizer. The AI recommendation was accurate for my wheat crop. Quick delivery and reasonable price compared to local market.',
  },
];

export const similarProducts = [
  {
    id: 'iffco-urea',
    name: 'IFFCO Urea',
    brand: 'IFFCO',
    image: require('../../assets/bazar/product2.jpg'),
    price: 380,
    oldPrice: 420,
    rating: 4.7,
  },
  {
    id: 'npk-19',
    name: 'NPK 19-19-19',
    brand: 'IFFCO',
    image: require('../../assets/bazar/product3.jpg'),
    price: 450,
    oldPrice: 560,
    rating: 4.9,
  },
];

export const defaultProduct = allProducts[0];