export const LABOUR_CATEGORIES = [
  {id: 'all', label: 'All', icon: '👥'},
  {id: 'sowing', label: 'Sowing', icon: '🌱'},
  {id: 'harvesting', label: 'Harvesting', icon: '🌾'},
  {id: 'weeding', label: 'Weeding', icon: '🌿'},
  {id: 'irrigation', label: 'Irrigation', icon: '💧'},
  {id: 'tractor', label: 'Tractor Helper', icon: '🚜'},
  {id: 'loading', label: 'Loading', icon: '📦'},
];

export const AVAILABLE_WORKERS = [
  {
    id: 'ram-pawar',
    name: 'Ram Pawar',
    category: 'harvesting',
    skills: ['Weeding', 'Harvesting', 'Sowing'],
    experience: '5 Yrs Exp',
    rating: '4.8',
    reviews: 125,
    distance: '2.1 km Away',
    dailyWage: 600,
    hourlyWage: 80,
    verified: true,
    availableToday: true,
    favourite: false,
    image: require('../../assets/labour/worker-1.jpg'),
    owner: 'Ram Pawar',
  },
  {
    id: 'shankar-jadhav',
    name: 'Shankar Jadhav',
    category: 'sowing',
    skills: ['Spraying', 'Cutting', 'Loading'],
    experience: '4 Yrs Exp',
    rating: '4.6',
    reviews: 98,
    distance: '3.4 km Away',
    dailyWage: 650,
    hourlyWage: 85,
    verified: true,
    availableToday: true,
    favourite: false,
    image: require('../../assets/labour/worker-1.jpg'),
    owner: 'Shankar Jadhav',
  },
  {
    id: 'mangal-bhosale',
    name: 'Mangal Bhosale',
    category: 'tractor',
    skills: ['Tractor Assistance', 'Weeding'],
    experience: '3 Yrs Exp',
    rating: '4.7',
    reviews: 110,
    distance: '4.2 km Away',
    dailyWage: 550,
    hourlyWage: 75,
    verified: true,
    availableToday: true,
    favourite: false,
    image: require('../../assets/labour/worker-1.jpg'),
    owner: 'Mangal Bhosale',
  },
];

export const RECENT_LABOUR_BOOKINGS = [
  {
    id: 'bk-1',
    name: 'Ram Pawar',
    activity: 'Harvesting',
    price: '₹2,400',
    date: '12 Jun 2025',
    image: require('../../assets/labour/worker-1.jpg'),
  },
  {
    id: 'bk-2',
    name: 'Shankar Jadhav',
    activity: 'Sowing',
    price: '₹2,600',
    date: '05 Jun 2025',
    image: require('../../assets/labour/worker-1.jpg'),
  },
];